# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [(main|release|task|feature|bugfix|hotfix|BUGFIX)/.*]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: alpine-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      # Builds the program
      - name: Builds the program
        run: |
          go build main.go

      # Runs the program
      - name: Runs the program
        run: |
          go run main.go
